apiVersion: v1
kind: Service
metadata:
  name: taskflow-backend-service
  namespace: dev
spec:
  type: ClusterIP
  selector:
    app: taskflow
    tier: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80