apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskflow-backend
  namespace: dev
  labels:
    app: taskflow
    tier: backend
spec:
  replicas: 3
  selector: 
    matchLabels:
      app: taskflow
      tier: backend
  template:
    metadata:
      labels:
        app: taskflow
        tier: backend
    spec:
      containers:
      - name: taskflow-backend
        image: adrielmaximus/taskflow-back-end:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
        env:
        - name: NODE_ENV
          value: "production"
