apiVersion: v1
kind: Service
metadata:
  name: taskflow-backend-service
spec:
  type: {{ .Values.backend.service.type }}
  selector:
    app: taskflow
    tier: backend
  ports:
    - protocol: TCP
      port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.targetPort }}