apiVersion: v1
kind: Service
metadata:
  name: taskflow-frontend-service
spec:
  type: {{ .Values.frontend.service.type }}
  selector:
    app: taskflow
    tier: frontend
  ports:
    - protocol: TCP
      port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.targetPort }}